### PR TITLE
Update to latest bootswatch templates

### PR DESCRIPTION
**Pull request by sandrokeil**
- Supports search and some minor optimizations
- We need Bookdown dev version for search

### CODE REVIEW

**Comment by prolic** [comment]
Search does not seem to work

**Comment by prolic** [comment]
Maybe it's because `http://localhost:8080/index.json` returned 404 ?

**Comment by sandrokeil** [comment]
> Search does not seem to work

Are you sure you are up2date? The `index.json` file is generated by Bookdown.

**Comment by prolic** [comment]
Well I see the search field. Is there something more to use that update?

Am 27.01.2017 00:31 schrieb "Sandro Keil" <notifications@github.com>:

**Comment by sandrokeil** [comment]
Only `composer update` to get the new Bookdown dev version

**Pull request merged**
